# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d9dfbe69d2b40763c8a4a28a435b01ebd8615e2e62d046d48d18547cffc02c8a29e7989879f719940a1cec975f2573c692457d620a8ff5a1769a665ef828f9d

test:
  secret_key_base: d03adbf8dc83db867b597e9e9a38ee160543d5db441f8882bc35cbf124d20a537bcb06139664f50232cb4c0663a7e3d63f7b9557bd06a65d419b3137cafe70fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
